version: '3'

services:
  backend:
    build: 
      context: ./backend
    command: bash -c "python3 manage.py collectstatic --noinput && gunicorn bugphile.wsgi --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
  
  frontend:
    build:
      context: ./frontend
    command: npm run build
    volumes:
      - frontend_build:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/build
      - ./backend/backend-static:/backend/backend-static
      - ./backend/media:/backend/media
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
