version: '3'

services:
  backend:
    build: 
      context: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
  
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./frontend/src:/frontend/src

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/backend-static:/backend/backend-static
      - ./backend/media:/backend/media
    depends_on:
      - backend
      - frontend
