# Generated by Django 4.0 on 2022-04-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugphile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='chemical_formula',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
