# Generated by Django 4.0 on 2022-04-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugphile_app', '0002_chemical_chemical_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='handling',
            name='msds',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
