# Generated by Django 4.0 on 2022-04-08 12:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugphile_app', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cas_number', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical', to='bugphile_app.category')),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bugphile_app.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Handling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msds', ckeditor.fields.RichTextField()),
                ('chemical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handling', to='bugphile_app.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', ckeditor.fields.RichTextField()),
                ('category_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_1', to='bugphile_app.category')),
                ('category_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_2', to='bugphile_app.category')),
            ],
            options={
                'unique_together': {('category_1', 'category_2')},
            },
        ),
    ]
