# Generated by Django 4.0 on 2022-04-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugphile_app', '0003_handling_msds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibility',
            name='report',
            field=models.TextField(),
        ),
    ]
